# Generated by Django 5.2.3 on 2025-07-18 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttask',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='studenttask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='assigned_supervisor',
        ),
        migrations.AddField(
            model_name='oncampussupervisor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_tasks_received', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='oncampussupervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_oncampus_supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onstationsupervisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_onstation_supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='supervisor_oncampus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oncampus_students', to='users.supervisorprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='supervisor_onstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onstation_students', to='users.supervisorprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users_supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supervisorupload',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supervisorupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='StudentTask',
        ),
    ]
