# Generated by Django 5.2.3 on 2025-07-27 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentresource',
            name='description',
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strengths', models.TextField()),
                ('benefits_personal', models.TextField()),
                ('org_benefits', models.TextField()),
                ('community_benefits', models.TextField()),
                ('relevance', models.TextField()),
                ('constraint', models.TextField()),
                ('solution', models.TextField()),
                ('suggestions', models.TextField()),
                ('knowledge', models.TextField()),
                ('skills', models.TextField()),
                ('supervision', models.TextField()),
                ('evaluation_method', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
    ]
