# Generated by Django 5.2.3 on 2025-07-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_departmentresource_description_evaluationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
            preserve_default=False,
        ),
    ]
