# Generated by Django 5.2.3 on 2025-07-26 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_departmentresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='general_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/general/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='technical_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/technical/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='uploaded_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='users.studentprofile')),
            ],
        ),
    ]
