# Generated by Django 5.2.3 on 2025-07-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_supervisorprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
    ]
