# Generated by Django 5.2.3 on 2025-06-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
