# Generated by Django 5.2.3 on 2025-07-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_evaluationform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='place',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='trainee_signature',
        ),
        migrations.AddField(
            model_name='logentry',
            name='company_place_institution',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
