# Generated by Django 5.2.3 on 2025-07-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_remove_logentry_institution_remove_logentry_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
