# Generated by Django 5.2.3 on 2025-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_uploadedfile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationform',
            old_name='student_feedback',
            new_name='benefits_personal',
        ),
        migrations.RenameField(
            model_name='evaluationform',
            old_name='supervisor_comments',
            new_name='community_benefits',
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='constraint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='evaluation_method',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='knowledge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='org_benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='relevance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='supervision',
            field=models.TextField(blank=True),
        ),
    ]
